# Generated by Django 2.1 on 2018-08-10 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, unique=True),
        ),
    ]
