# Generated by Django 2.1 on 2018-08-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0004_auto_20180810_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
